#!/bin/bash

groupmod -o -g "${PGID}" rssfeedtoolbox
usermod -o -u "${PUID}" rssfeedtoolbox

chown -R rssfeedtoolbox:rssfeedtoolbox \
    "${HOME}" \
    /app \
    /public \
    /config \
    /var/lib/nginx \
    /var/log/nginx
chown rssfeedtoolbox:rssfeedtoolbox /etc/hosts /tmp

nginx

umask "${UMASK}"

alembic upgrade head && uvicorn main:app