"""some_change

Revision ID: 14bd0084072b
Revises: cee345430818
Create Date: 2024-07-15 21:25:18.689315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '14bd0084072b'
down_revision: Union[str, None] = 'cee345430818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_title', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('match_season', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('match_team', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribe', schema=None) as batch_op:
        batch_op.drop_column('match_team')
        batch_op.drop_column('match_season')
        batch_op.drop_column('match_title')

    # ### end Alembic commands ###
