"""subscribe_field_change

Revision ID: 3c0030c41e5e
Revises: bcd9cddf8385
Create Date: 2024-08-15 10:43:14.311957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0030c41e5e'
down_revision: Union[str, None] = 'bcd9cddf8385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('media_tmdb_id', sa.Integer(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('download_path')
        batch_op.drop_column('transfer_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('download_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('media_tmdb_id')
        batch_op.drop_column('media_name')

    # ### end Alembic commands ###
