"""some_change

Revision ID: 6382b52519d9
Revises: 14bd0084072b
Create Date: 2024-07-23 14:19:31.690572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6382b52519d9'
down_revision: Union[str, None] = '14bd0084072b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torrent_list', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.drop_column('torrent_list')

    # ### end Alembic commands ###
