"""init

Revision ID: 861e16a8530e
Revises: 
Create Date: 2024-07-11 11:34:18.681880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861e16a8530e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('cookie', sa.String(), nullable=False),
    sa.Column('time_out', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('site_rss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('site_rss_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('include', sa.String(), nullable=True),
    sa.Column('exclude', sa.String(), nullable=True),
    sa.Column('download_path', sa.String(), nullable=True),
    sa.Column('transfer_path', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['site_rss_id'], ['site_rss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscribe_id', sa.Integer(), nullable=False),
    sa.Column('torrent_hash', sa.String(), nullable=False),
    sa.Column('torrent_name', sa.String(), nullable=False),
    sa.Column('torrent_desc', sa.String(), nullable=True),
    sa.Column('save_path', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscribe_id'], ['subscribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download_history')
    op.drop_table('subscribe')
    op.drop_table('site_rss')
    op.drop_table('user')
    op.drop_table('site')
    # ### end Alembic commands ###
