"""some_change

Revision ID: bcd9cddf8385
Revises: 9993bada828c
Create Date: 2024-08-14 16:15:07.670713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd9cddf8385'
down_revision: Union[str, None] = '9993bada828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscribe_id', sa.Integer(), nullable=False),
    sa.Column('rss_title', sa.String(), nullable=False),
    sa.Column('rss_pubdate', sa.DateTime(), nullable=False),
    sa.Column('downloader_id', sa.Integer(), nullable=False),
    sa.Column('torrent_hash', sa.String(), nullable=False),
    sa.Column('torrent_file', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['downloader_id'], ['downloader.id'], ),
    sa.ForeignKeyConstraint(['subscribe_id'], ['subscribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscribe_history_id', sa.Integer(), nullable=False),
    sa.Column('source_file_path', sa.String(), nullable=False),
    sa.Column('target_file_path', sa.String(), nullable=False),
    sa.Column('transfer_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscribe_history_id'], ['subscribe_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('download_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subscribe_id', sa.INTEGER(), nullable=False),
    sa.Column('torrent_hash', sa.VARCHAR(), nullable=False),
    sa.Column('create_at', sa.DATETIME(), nullable=False),
    sa.Column('rss_title', sa.VARCHAR(), nullable=False),
    sa.Column('rss_guid', sa.VARCHAR(), nullable=True),
    sa.Column('torrent_list', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['subscribe_id'], ['subscribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transfer_record')
    op.drop_table('subscribe_history')
    # ### end Alembic commands ###
