"""some_change

Revision ID: cee345430818
Revises: 20994812c6bc
Create Date: 2024-07-15 20:39:01.454216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee345430818'
down_revision: Union[str, None] = '20994812c6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_rss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_pub', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_rss', schema=None) as batch_op:
        batch_op.drop_column('latest_pub')

    # ### end Alembic commands ###
